require "plugins.options"
require "plugins.keymaps"
require "plugins.lsp"
require "plugins.plugins"
require "plugins.colorscheme"
require "plugins.cmp"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.gitsigns"
require "plugins.nvim-tree"
require "plugins.bufferline"
require "plugins.toggleterm"
-- require "plugins.indent-blankline"
require "plugins.lualine"
require "plugins.dap"
