vim.wo.number = true -- set number lines
vim.opt.relativenumber = true -- set relative lines
vim.o.clipboard = 'unnamedplus' -- share clipboard with os
vim.o.wrap = false -- don`t let it wrap
vim.o.linebreak = true -- Companion to wrap, don`t split words
vim.o.autoindent = true -- self explanatory
vim.o.ignorecase = true -- Case insensity unless starts with Capital
vim.o.shiftwidth = 4 -- again, self explanatory
vim.o.tabstop = 4 -- 4 spaces for tab
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.opt.backup = false                          -- creates a backup file
vim.opt.cmdheight = 2                           -- more space in the neovim command line for displaying messages
vim.opt.completeopt = { "menuone", "noselect" } -- mostly just for cmp
vim.opt.conceallevel = 0                        -- so that `` is visible in markdown files
vim.opt.fileencoding = "utf-8"                  -- the encoding written to a file
vim.opt.hlsearch = false                        -- highlight all matches on previous search pattern
vim.opt.ignorecase = true                       -- ignore case in search patterns
vim.opt.mouse = "a"                             -- allow the mouse to be used in neovim
vim.opt.pumheight = 10                          -- pop up menu height
vim.opt.showmode = false                        -- we don't need to see things like -- INSERT -- anymore
vim.opt.showtabline = 2                         -- always show tabs
vim.opt.smartcase = true                        -- smart case
vim.opt.smartindent = true                      -- make indenting smarter again
vim.opt.splitbelow = true                       -- force all horizontal splits to go below current window
vim.opt.splitright = true                       -- force all vertical splits to go to the right of current window
vim.opt.swapfile = false                        -- creates a swapfile
vim.opt.termguicolors = true                    -- set term gui colors (most terminals support this)
vim.opt.timeoutlen = 1000                       -- time to wait for a mapped sequence to complete (in milliseconds)
vim.opt.undofile = true                         -- enable persistent undo
vim.opt.updatetime = 300                        -- faster completion (4000ms default)
vim.opt.writebackup = false                     -- if a file is being edited by another program, it is not allowed to be edited
vim.opt.expandtab = true                        -- convert tabs to spaces
vim.opt.shiftwidth = 2                          -- the number of spaces inserted for each indentation
vim.opt.tabstop = 2                             -- insert 2 spaces for a tab
vim.opt.cursorline = false                      -- highlight the current line
vim.opt.number = true                           -- set numbered lines
vim.opt.relativenumber = true                   -- set relative numbered lines
vim.opt.numberwidth = 4                         -- set number column width to 4 (default 4)
vim.opt.signcolumn = "yes"                      -- always show the sign column
vim.opt.wrap = false                            -- display lines as one long line
vim.opt.scrolloff = 8                           -- minimal lines to keep above and below the cursor
vim.opt.sidescrolloff = 8                       -- minimal columns to keep to the left and right of the cursor
vim.opt.guifont = "monospace:h17"               -- the font used in graphical neovim applications


